// GENERATED by tools/generate_library_contract.py; do not edit.
// ignore_for_file: non_constant_identifier_names, prefer_single_quotes

class Instrument {
  final String id;
  final String? title;
  final String kind;
  final int? year;
  final String jurisdiction;
  final String status;
  final String? source_url;
  final int document_id;
  final String source_hash;
  const Instrument({required this.id, required this.title, required this.kind, required this.year, required this.jurisdiction, required this.status, required this.source_url, required this.document_id, required this.source_hash});
  factory Instrument.fromJson(Map<String, dynamic> json) => Instrument(
    id: json['id'] as String,
    title: json['title'] == null ? null : json['title'] as String,
    kind: json['kind'] as String,
    year: json['year'] == null ? null : json['year'] as int,
    jurisdiction: json['jurisdiction'] as String,
    status: json['status'] as String,
    source_url: json['source_url'] == null ? null : json['source_url'] as String,
    document_id: json['document_id'] as int,
    source_hash: json['source_hash'] as String,
  );
}

class Node {
  final String id;
  final String instrument_id;
  final String? parent_id;
  final String? label;
  final String? heading;
  final String? marginal_note;
  final String kind;
  final int ordinal;
  final int? first_page;
  final bool has_children;
  const Node({required this.id, required this.instrument_id, required this.parent_id, required this.label, required this.heading, required this.marginal_note, required this.kind, required this.ordinal, required this.first_page, required this.has_children});
  factory Node.fromJson(Map<String, dynamic> json) => Node(
    id: json['id'] as String,
    instrument_id: json['instrument_id'] as String,
    parent_id: json['parent_id'] == null ? null : json['parent_id'] as String,
    label: json['label'] == null ? null : json['label'] as String,
    heading: json['heading'] == null ? null : json['heading'] as String,
    marginal_note: json['marginal_note'] == null ? null : json['marginal_note'] as String,
    kind: json['kind'] as String,
    ordinal: json['ordinal'] as int,
    first_page: json['first_page'] == null ? null : json['first_page'] as int,
    has_children: json['has_children'] as bool,
  );
}

class Ancestor {
  final String id;
  final String? label;
  final String? heading;
  final String kind;
  const Ancestor({required this.id, required this.label, required this.heading, required this.kind});
  factory Ancestor.fromJson(Map<String, dynamic> json) => Ancestor(
    id: json['id'] as String,
    label: json['label'] == null ? null : json['label'] as String,
    heading: json['heading'] == null ? null : json['heading'] as String,
    kind: json['kind'] as String,
  );
}

class Provision {
  final String id;
  final String instrument_id;
  final String? parent_id;
  final String? label;
  final String? heading;
  final String? marginal_note;
  final String kind;
  final int ordinal;
  final int? first_page;
  final bool has_children;
  final String? text_en;
  final String? text_ur;
  final String? operation;
  final String? valid_from;
  final String? valid_to;
  final Instrument instrument;
  final List<Ancestor> ancestors;
  const Provision({required this.id, required this.instrument_id, required this.parent_id, required this.label, required this.heading, required this.marginal_note, required this.kind, required this.ordinal, required this.first_page, required this.has_children, required this.text_en, required this.text_ur, required this.operation, required this.valid_from, required this.valid_to, required this.instrument, required this.ancestors});
  factory Provision.fromJson(Map<String, dynamic> json) => Provision(
    id: json['id'] as String,
    instrument_id: json['instrument_id'] as String,
    parent_id: json['parent_id'] == null ? null : json['parent_id'] as String,
    label: json['label'] == null ? null : json['label'] as String,
    heading: json['heading'] == null ? null : json['heading'] as String,
    marginal_note: json['marginal_note'] == null ? null : json['marginal_note'] as String,
    kind: json['kind'] as String,
    ordinal: json['ordinal'] as int,
    first_page: json['first_page'] == null ? null : json['first_page'] as int,
    has_children: json['has_children'] as bool,
    text_en: json['text_en'] == null ? null : json['text_en'] as String,
    text_ur: json['text_ur'] == null ? null : json['text_ur'] as String,
    operation: json['operation'] == null ? null : json['operation'] as String,
    valid_from: json['valid_from'] == null ? null : json['valid_from'] as String,
    valid_to: json['valid_to'] == null ? null : json['valid_to'] as String,
    instrument: Instrument.fromJson(json['instrument'] as Map<String, dynamic>),
    ancestors: (json['ancestors'] as List).map((v) => Ancestor.fromJson(v as Map<String, dynamic>)).toList(),
  );
}

class InstrumentPage {
  final String as_of;
  final String mode;
  final String notice;
  final List<Instrument> items;
  final String? next_cursor;
  const InstrumentPage({required this.as_of, required this.mode, required this.notice, required this.items, required this.next_cursor});
  factory InstrumentPage.fromJson(Map<String, dynamic> json) => InstrumentPage(
    as_of: json['as_of'] as String,
    mode: json['mode'] as String,
    notice: json['notice'] as String,
    items: (json['items'] as List).map((v) => Instrument.fromJson(v as Map<String, dynamic>)).toList(),
    next_cursor: json['next_cursor'] == null ? null : json['next_cursor'] as String,
  );
}

class NodePage {
  final String as_of;
  final String mode;
  final String notice;
  final List<Node> items;
  final String? next_cursor;
  const NodePage({required this.as_of, required this.mode, required this.notice, required this.items, required this.next_cursor});
  factory NodePage.fromJson(Map<String, dynamic> json) => NodePage(
    as_of: json['as_of'] as String,
    mode: json['mode'] as String,
    notice: json['notice'] as String,
    items: (json['items'] as List).map((v) => Node.fromJson(v as Map<String, dynamic>)).toList(),
    next_cursor: json['next_cursor'] == null ? null : json['next_cursor'] as String,
  );
}

class InstrumentResult {
  final String as_of;
  final String mode;
  final String notice;
  final Instrument item;
  const InstrumentResult({required this.as_of, required this.mode, required this.notice, required this.item});
  factory InstrumentResult.fromJson(Map<String, dynamic> json) => InstrumentResult(
    as_of: json['as_of'] as String,
    mode: json['mode'] as String,
    notice: json['notice'] as String,
    item: Instrument.fromJson(json['item'] as Map<String, dynamic>),
  );
}

class ProvisionResult {
  final String as_of;
  final String mode;
  final String notice;
  final Provision item;
  const ProvisionResult({required this.as_of, required this.mode, required this.notice, required this.item});
  factory ProvisionResult.fromJson(Map<String, dynamic> json) => ProvisionResult(
    as_of: json['as_of'] as String,
    mode: json['mode'] as String,
    notice: json['notice'] as String,
    item: Provision.fromJson(json['item'] as Map<String, dynamic>),
  );
}
