"""Emit the preview OpenAPI and matching Dart DTOs from real route schemas.

Run after API changes; --check is the CI drift gate. Generated files are not edited.
"""
import argparse
import json
from pathlib import Path
from nizam.api.library import create_app

ROOT = Path(__file__).resolve().parents[1]


def dart_type(schema):
    if 'anyOf' in schema:
        choices = [s for s in schema['anyOf'] if s.get('type') != 'null']
        return dart_type(choices[0]) + '?'
    if '$ref' in schema:
        return schema['$ref'].split('/')[-1]
    if schema.get('type') == 'array':
        return f"List<{dart_type(schema['items'])}>"
    return {'integer':'int', 'boolean':'bool', 'number':'double', 'object':'Map<String, dynamic>'}.get(schema.get('type'), 'String')


def parse_value(schema, value):
    if 'anyOf' in schema:
        child = next(s for s in schema['anyOf'] if s.get('type') != 'null')
        return f"{value} == null ? null : {parse_value(child, value)}"
    if '$ref' in schema:
        return f"{dart_type(schema)}.fromJson({value} as Map<String, dynamic>)"
    if schema.get('type') == 'array':
        return f"({value} as List).map((v) => {parse_value(schema['items'], 'v')}).toList()"
    return f"{value} as {dart_type(schema)}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    spec = create_app().openapi()
    names = ['Instrument', 'Node', 'Ancestor', 'Provision', 'InstrumentPage', 'NodePage', 'InstrumentResult', 'ProvisionResult']
    lines = ['// GENERATED by tools/generate_library_contract.py; do not edit.',
             '// ignore_for_file: non_constant_identifier_names, prefer_single_quotes', '']
    for name in names:
        props = spec['components']['schemas'][name]['properties']
        lines += [f'class {name} {{']
        for key, schema in props.items():
            lines += [f'  final {dart_type(schema)} {key};']
        lines += [f'  const {name}({{'+', '.join('required this.'+k for k in props)+'});',
                  f'  factory {name}.fromJson(Map<String, dynamic> json) => {name}(']
        for key, schema in props.items():
            lines += [f'    {key}: {parse_value(schema, "json["+repr(key)+"]")},']
        lines += ['  );', '}', '']
    outputs = {'openapi/library-preview.json': json.dumps(spec, indent=2)+'\n',
               'apps/mobile/lib/contracts/library_models.g.dart': '\n'.join(lines)}
    for path, content in outputs.items():
        target = ROOT/path
        if args.check:
            assert target.read_text(encoding='utf8') == content, f'Contract drift: {path}'
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding='utf8')
            print(path)


if __name__ == '__main__': main()
